"""Phase 1 — data spine: users, paper_accounts, bars, ingest_state, gap_events.

Phase 1 scaffolded these SQLAlchemy models but never wired up Alembic, so this
is the first migration to actually exist. Written by hand (not autogenerated)
so it can be reviewed without a live database connection.

Revision ID: 0001_phase1_data_spine
Revises:
Create Date: 2026-08-29
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001_phase1_data_spine"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column("email", sa.String(255), nullable=False, unique=True),
        sa.Column("display_name", sa.String(120)),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("role", sa.String(16), nullable=False, server_default="requester"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False,
            server_default=sa.func.now(),
        ),
    )

    op.create_table(
        "paper_accounts",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id", sa.Uuid(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column(
            "starting_cash", sa.Numeric(18, 2), nullable=False,
            server_default="100000.00",
        ),
        sa.Column("cash", sa.Numeric(18, 2), nullable=False),
        sa.Column("equity", sa.Numeric(18, 2), nullable=False),
        sa.Column("benchmark_symbol", sa.String(16), nullable=False, server_default="SPY"),
        sa.Column("benchmark_start_price", sa.Numeric(18, 4)),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False,
            server_default=sa.func.now(),
        ),
    )

    op.create_table(
        "bars",
        sa.Column("symbol", sa.String(16), primary_key=True),
        sa.Column("timeframe", sa.String(8), primary_key=True),
        sa.Column("ts", sa.DateTime(timezone=True), primary_key=True),
        sa.Column("open", sa.Numeric(18, 4), nullable=False),
        sa.Column("high", sa.Numeric(18, 4), nullable=False),
        sa.Column("low", sa.Numeric(18, 4), nullable=False),
        sa.Column("close", sa.Numeric(18, 4), nullable=False),
        sa.Column("volume", sa.BigInteger, nullable=False),
        sa.Column("vwap", sa.Numeric(18, 4)),
        sa.Column("trade_count", sa.Integer),
        sa.Column("source", sa.String(24), nullable=False, server_default="alpaca_iex"),
    )
    op.create_index(
        "ix_bars_symbol_tf_ts_desc", "bars", ["symbol", "timeframe", sa.text("ts DESC")]
    )

    # TimescaleDB hypertable — BUILD_SPEC §3, §5. Only meaningful against the
    # timescale/timescaledb Postgres image in docker-compose.yml; skipped
    # entirely on any other backend (e.g. SQLite in tests).
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
        op.execute("SELECT create_hypertable('bars', 'ts', if_not_exists => TRUE)")

    op.create_table(
        "ingest_state",
        sa.Column("symbol", sa.String(16), primary_key=True),
        sa.Column("timeframe", sa.String(8), primary_key=True, server_default="1Min"),
        sa.Column("last_bar_ts", sa.DateTime(timezone=True)),
        sa.Column("last_message_at", sa.DateTime(timezone=True)),
        sa.Column("subscribed_at", sa.DateTime(timezone=True)),
        sa.Column("backfilled_through", sa.DateTime(timezone=True)),
        sa.Column("gap_count", sa.Integer, nullable=False, server_default="0"),
    )

    op.create_table(
        "gap_events",
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        sa.Column("symbol", sa.String(16), nullable=False),
        sa.Column("timeframe", sa.String(8), nullable=False, server_default="1Min"),
        sa.Column("gap_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gap_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expected_bars", sa.Integer, nullable=False),
        sa.Column("filled_bars", sa.Integer, nullable=False, server_default="0"),
        sa.Column("resolved", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("detail", sa.Text),
        sa.Column(
            "detected_at", sa.DateTime(timezone=True), nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True)),
    )


def downgrade() -> None:
    op.drop_table("gap_events")
    op.drop_table("ingest_state")
    op.drop_index("ix_bars_symbol_tf_ts_desc", table_name="bars")
    op.drop_table("bars")
    op.drop_table("paper_accounts")
    op.drop_table("users")
